### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by mix345** [liuff19/Physics3D#3]
Thank you very much for sharing your great work.

I try to run simulation.py by the example command.
```
python simulation.py --model_path ./model/ball/ --prompt "a basketball falling down" --output_path ./output --physics_config ./config/ball_config.json
```

I got the following error.

```
Traceback (most recent call last):
  File "/home/max/research/Physics3D/simulation.py", line 46, in <module>
    from video_distillation.guidance import ModelscopeGuidance
  File "/home/max/research/Physics3D/video_distillation/guidance.py", line 11, in <module>
    from video_distillation.prompt_processors import PromptProcessorOutput
ModuleNotFoundError: No module named 'video_distillation.prompt_processors'
```
I do not find any prompt_processors.py under video_distillation directory, or PromptProcessorOutput function within this repository.
Could you tell me how to fix this?

Thank you.

**Comment by cccrystalyang** [comment]
Hi, I've encountered the same problem, has anyone solved it?

**Comment by bjxdw** [comment]
Same problem here. Has anyone solved it?

**Comment by zy-lazytitan** [comment]
Same problem here. Has anyone solved it?

**Comment by ChangjingLiu** [comment]
same problem
